### ISSUE TITLE
PHP fatal, something missing

### ISSUE THREAD

**Issue by cxj** [producerphp/producer.githooks#1]
I feel like there's a critical line of code missing, or something.  The autoloader is not getting run, perhaps?

```sh
php ./vendor/producer/githooks/bin/set-hooks.php
PHP Fatal error:  Uncaught Error: Class 'Producer\Githooks\SetHooks' not found in /Users/chris/project1/vendor/producer/githooks/bin/set-hooks.php:4
```

**Comment by pmjones** [comment]
Sorry about that, Chris, I left some local changes uncommitted. I have committed and pushed them to 0.x@dev. Thanks for raising the issue. Try again, and let me know how it goes?

**Comment by cxj** [comment]
It works fine now with the update.  Thanks much for the quick fix!
